// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_wnkBnBpktbC32ZWz9ILbwo_kdmfaHE',
    appId: '1:35509025483:android:ce7ed55fca24945185794e',
    messagingSenderId: '35509025483',
    projectId: 'travaly-project',
    storageBucket: 'travaly-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzplzDaKjsX1o3DALcT7lw2h0YxcL_I_o',
    appId: '1:35509025483:ios:5d29d8a6fc5c7d9c85794e',
    messagingSenderId: '35509025483',
    projectId: 'travaly-project',
    storageBucket: 'travaly-project.firebasestorage.app',
    iosBundleId: 'com.example.travalyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmmliBE_qrBMNLU_mZp_sx26ubEasOJdw',
    appId: '1:35509025483:web:ddd1d8689e0359cb85794e',
    messagingSenderId: '35509025483',
    projectId: 'travaly-project',
    authDomain: 'travaly-project.firebaseapp.com',
    storageBucket: 'travaly-project.firebasestorage.app',
  );
}
